# Generated by Django 6.0.3 on 2026-04-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperateDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='operate/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Файл аналитики',
                'verbose_name_plural': 'Файлы аналитики',
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
    ]
