# Generated by Django 6.0.3 on 2026-04-07 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatedatafile',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Обработан'),
        ),
        migrations.AddField(
            model_name='operatedatafile',
            name='processing_error',
            field=models.TextField(blank=True, default='', verbose_name='Ошибка обработки'),
        ),
        migrations.CreateModel(
            name='OperateRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_number', models.IntegerField(blank=True, null=True, verbose_name='Номер строки в источнике')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='Месяц')),
                ('subdivision', models.CharField(blank=True, default='', max_length=255, verbose_name='Подразделение')),
                ('block', models.CharField(blank=True, default='', max_length=255, verbose_name='Блок')),
                ('process_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Передел')),
                ('machine_brand', models.CharField(blank=True, default='', max_length=255, verbose_name='Марка техники')),
                ('machine_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Марка машины')),
                ('machine_inventory', models.CharField(blank=True, default='', max_length=255, verbose_name='Инв. №')),
                ('work_volume', models.FloatField(blank=True, null=True, verbose_name='Объем работ')),
                ('corrected_work_volume', models.FloatField(blank=True, null=True, verbose_name='Объем работ скорректированный')),
                ('work_time', models.FloatField(blank=True, null=True, verbose_name='Время работы')),
                ('downtime', models.FloatField(blank=True, null=True, verbose_name='Время простоя')),
                ('transportation_distance', models.FloatField(blank=True, null=True, verbose_name='Откатка, м')),
                ('shift_master', models.CharField(blank=True, default='', max_length=255, verbose_name='Горный мастер')),
                ('operator_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Машинист')),
                ('assistant_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Помощник')),
                ('downtime_reason', models.TextField(blank=True, default='', verbose_name='Причина простоя')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='Сырые данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('data_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='operate.operatedatafile', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Строка аналитики',
                'verbose_name_plural': 'Строки аналитики',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['subdivision'], name='operate_ope_subdivi_b8e27c_idx'), models.Index(fields=['date'], name='operate_ope_date_36f451_idx'), models.Index(fields=['year'], name='operate_ope_year_17d44b_idx'), models.Index(fields=['month'], name='operate_ope_month_03002f_idx'), models.Index(fields=['subdivision', 'year'], name='operate_ope_subdivi_a040c2_idx'), models.Index(fields=['subdivision', 'process_name'], name='operate_ope_subdivi_e816bc_idx')],
            },
        ),
    ]
