# Generated by Django 6.0.3 on 2026-04-15 08:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('hh_candidate', models.CharField(blank=True, max_length=255, verbose_name='Соискатель по вакансии на hh.ru')),
                ('position_name', models.CharField(max_length=255, verbose_name='Должность (название в Поиск золото)')),
                ('contacts', models.TextField(blank=True, verbose_name='Контакты')),
                ('medical_commission', models.CharField(blank=True, max_length=255, verbose_name='Мед комиссия')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('birth_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('qualification', models.TextField(blank=True, verbose_name='Квалификация, наличие удостоверения на сайте')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('referral_to_mo', models.CharField(blank=True, max_length=255, verbose_name='Направление на МО')),
                ('refusal_reason', models.TextField(blank=True, verbose_name='Примечание или причина отказа')),
                ('ticket', models.CharField(blank=True, max_length=255, verbose_name='Билет')),
                ('estimated_arrival_date', models.DateField(blank=True, null=True, verbose_name='Расчетная дата приезда')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_records_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_records_updated', to=settings.AUTH_USER_MODEL, verbose_name='Последний редактор')),
            ],
            options={
                'verbose_name': 'Кадровая карточка',
                'verbose_name_plural': 'Кадровые карточки',
                'ordering': ['-date', 'full_name', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PersonnelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='personnel/%Y/%m/%d/', verbose_name='Файл')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel_documents_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='personnel.personnelrecord', verbose_name='Кадровая карточка')),
            ],
            options={
                'verbose_name': 'Документ кадровой карточки',
                'verbose_name_plural': 'Документы кадровых карточек',
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
    ]
