# Generated by Django 6.0.3 on 2026-04-16 07:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='№')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('hh_vacancy', models.CharField(blank=True, max_length=255, verbose_name='Соискатель по вакансии на hh.ru')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('contacts', models.CharField(blank=True, max_length=255, verbose_name='Контакты')),
                ('medical_commission', models.CharField(blank=True, choices=[('pending', 'Ожидает'), ('passed', 'Пройдена'), ('failed', 'Не пройдена')], default='pending', max_length=20, verbose_name='Мед комиссия')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('qualification', models.TextField(blank=True, verbose_name='Квалификация, наличие удостоверения на сайте')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('medical_referral', models.CharField(blank=True, max_length=255, verbose_name='Направление на МО')),
                ('refusal_reason', models.TextField(blank=True, verbose_name='Примечание или причина отказа')),
                ('ticket', models.CharField(blank=True, max_length=255, verbose_name='Билет')),
                ('stage', models.CharField(choices=[('cold_search', 'Холодный поиск'), ('response', 'Отклик'), ('phone_interview', 'Тел. интервью'), ('interview', 'Собеседование'), ('medical', 'Медкомиссия'), ('ticket', 'Билет'), ('hired', 'Трудоустроен'), ('rejected', 'Отказ')], default='cold_search', max_length=30, verbose_name='Этап')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
                'ordering': ['stage', 'sort_order', '-date', '-id'],
            },
        ),
        migrations.RemoveField(
            model_name='personnelrecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='personnelrecord',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='PersonnelDocument',
        ),
        migrations.DeleteModel(
            name='PersonnelRecord',
        ),
    ]
