# Generated by Django 6.0.3 on 2026-04-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_resumecandidate_remove_personnelrecord_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumecandidate',
            name='hh_last_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация HH'),
        ),
        migrations.AddField(
            model_name='resumecandidate',
            name='hh_resume_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='HH resume id'),
        ),
        migrations.AddField(
            model_name='resumecandidate',
            name='hh_resume_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на резюме HH'),
        ),
        migrations.AddField(
            model_name='resumecandidate',
            name='hh_source',
            field=models.CharField(blank=True, max_length=100, verbose_name='Источник HH'),
        ),
        migrations.AddField(
            model_name='resumecandidate',
            name='hh_vacancy_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='HH vacancy id'),
        ),
    ]
