# Generated by Django 6.0.3 on 2026-04-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_resumecandidate_hh_last_sync_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumecandidate',
            name='medical_referral',
        ),
        migrations.AlterField(
            model_name='resumecandidate',
            name='stage',
            field=models.CharField(choices=[('cold_search', 'Холодный поиск'), ('response', 'Отклик'), ('phone_interview', 'Тел. интервью'), ('interview', 'Собеседование'), ('medical', 'Медкомиссия'), ('ticket', 'Требуется покупка билетов'), ('hired', 'Трудоустроен'), ('rejected', 'Отказ')], default='response', max_length=30, verbose_name='Этап'),
        ),
    ]
