# Generated by Django 6.0.3 on 2026-04-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_remove_resumecandidate_medical_referral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumecandidate',
            name='otipb',
            field=models.CharField(blank=True, max_length=255, verbose_name='ОТИПБ'),
        ),
        migrations.AlterField(
            model_name='resumecandidate',
            name='stage',
            field=models.CharField(choices=[('cold_search', 'Холодный поиск'), ('response', 'Отклик'), ('phone_interview', 'Тел. интервью'), ('interview', 'Собеседование'), ('otipb', 'ОТИПБ'), ('medical', 'Медкомиссия'), ('ticket', 'Требуется покупка билетов'), ('hired', 'Трудоустроен'), ('rejected', 'Отказ')], default='response', max_length=30, verbose_name='Этап'),
        ),
    ]
