# Generated by Django 6.0.3 on 2026-04-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_resumecandidate_otipb_alter_resumecandidate_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumecandidate',
            name='stage',
            field=models.CharField(choices=[('response', 'Отклик'), ('phone_interview', 'Тел. интервью'), ('otipb', 'ОТИПБ'), ('hr_department', 'Отдел кадров'), ('ticket', 'Требуется покупка билетов'), ('hired', 'Трудоустроен')], default='response', max_length=30, verbose_name='Этап'),
        ),
    ]
