# Generated by Django 6.0.3 on 2026-04-19 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_resumecandidatedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('notify_email', models.EmailField(blank=True, max_length=254, verbose_name='Email для уведомлений')),
            ],
            options={
                'verbose_name': 'Этап подбора',
                'verbose_name_plural': 'Этапы подбора',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='resumecandidate',
            options={'ordering': ['sort_order', '-date', '-id'], 'verbose_name': 'Кандидат', 'verbose_name_plural': 'Кандидаты'},
        ),
        migrations.AlterField(
            model_name='resumecandidate',
            name='stage',
            field=models.ForeignKey(blank=True, db_column='stage', db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='personnel.resumestage', to_field='code', verbose_name='Этап'),
        ),
    ]
