# Generated by Django 6.0.3 on 2026-04-19 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_resumestage_alter_resumecandidate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumecandidate',
            options={'ordering': ['stage', 'sort_order', '-date', '-id'], 'verbose_name': 'Кандидат', 'verbose_name_plural': 'Кандидаты'},
        ),
        migrations.AddField(
            model_name='resumestage',
            name='responsible_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_stages', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='resumecandidate',
            name='stage',
            field=models.CharField(db_index=True, default='response', max_length=100, verbose_name='Этап'),
        ),
        migrations.AlterField(
            model_name='resumestage',
            name='code',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='resumestage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название этапа'),
        ),
        migrations.AlterField(
            model_name='resumestage',
            name='notify_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Дополнительный email для уведомлений'),
        ),
        migrations.AlterField(
            model_name='resumestage',
            name='sort_order',
            field=models.PositiveIntegerField(default=100, verbose_name='Порядок'),
        ),
    ]
