# Generated by Django 6.0.3 on 2026-04-24 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0009_alter_resumecandidate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumecandidate',
            name='work_experience',
            field=models.TextField(blank=True, verbose_name='Опыт работы'),
        ),
    ]
