# Generated by Django 6.0.3 on 2026-04-24 02:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0010_resumecandidate_work_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtipbHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=255, verbose_name='ФИО')),
                ('full_name_normalized', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='ФИО для поиска')),
                ('hh_vacancy', models.CharField(blank=True, max_length=255, verbose_name='Соискатель по вакансии на hh.ru')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('contacts', models.CharField(blank=True, max_length=255, verbose_name='Контакты')),
                ('medical_commission', models.CharField(blank=True, max_length=20, verbose_name='Мед комиссия')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('qualification', models.TextField(blank=True, verbose_name='Квалификация, наличие удостоверения на сайте')),
                ('work_experience', models.TextField(blank=True, verbose_name='Опыт работы')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('otipb', models.CharField(blank=True, max_length=255, verbose_name='ОТИПБ')),
                ('refusal_reason', models.TextField(blank=True, verbose_name='Примечание или причина отказа')),
                ('ticket', models.CharField(blank=True, max_length=255, verbose_name='Билет')),
                ('stage', models.CharField(blank=True, max_length=100, verbose_name='Этап')),
                ('source', models.CharField(blank=True, default='Карточка кандидата', max_length=255, verbose_name='Источник')),
                ('source_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата актуальности данных')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('source_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otipb_history_items', to='personnel.resumecandidate', verbose_name='Карточка кандидата')),
            ],
            options={
                'verbose_name': 'История ОТИПБ',
                'verbose_name_plural': 'История ОТИПБ',
                'ordering': ['-source_date', '-id'],
            },
        ),
    ]
