# Generated by Django 6.0.3 on 2026-04-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0011_otipbhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Строка Excel')),
                ('source_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='№ п/п из Excel')),
                ('source_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Дата из Excel')),
                ('full_name', models.CharField(db_index=True, max_length=255, verbose_name='ФИО')),
                ('full_name_normalized', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='ФИО для поиска')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('vacancy', models.CharField(blank=True, max_length=255, verbose_name='Вакансия')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Телефон')),
                ('qualification', models.TextField(blank=True, verbose_name='Квалификация, наличие удостоверения на сайте')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('medical_direction', models.TextField(blank=True, verbose_name='Направление на МО')),
                ('refusal_reason', models.TextField(blank=True, verbose_name='Примечание или причина отказа')),
                ('accepted_date', models.DateField(blank=True, null=True, verbose_name='Принят дата')),
                ('import_file_name', models.CharField(blank=True, max_length=255, verbose_name='Имя файла импорта')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата импорта')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Запись из файла кандидатов',
                'verbose_name_plural': 'Записи из файла кандидатов',
                'ordering': ['-source_date', '-id'],
                'indexes': [models.Index(fields=['full_name_normalized', '-source_date'], name='personnel_c_full_na_9c91bf_idx')],
            },
        ),
        migrations.DeleteModel(
            name='OtipbHistory',
        ),
    ]
