# Generated by Django 6.0.3 on 2026-04-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0012_candidatesourcerecord_delete_otipbhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesourcerecord',
            name='otipb',
            field=models.CharField(blank=True, max_length=255, verbose_name='ОТИПБ'),
        ),
    ]
