# Generated by Django 6.0.3 on 2026-04-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0013_candidatesourcerecord_otipb'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumecandidate',
            name='approval_department',
            field=models.CharField(blank=True, choices=[('', 'Не требуется'), ('mechanic_approval', 'ОГМ'), ('geology_approval', 'Геологический отдел'), ('transport_approval', 'Транспортный цех')], db_index=True, default='', max_length=100, verbose_name='Требуется согласование'),
        ),
        migrations.AlterField(
            model_name='resumecandidate',
            name='stage',
            field=models.CharField(db_index=True, default='phone_interview', max_length=100, verbose_name='Этап'),
        ),
    ]
