# Generated by Django 6.0.3 on 2026-04-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0015_resumecandidate_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumestage',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Этап процесса', 'verbose_name_plural': 'Этапы процесса'},
        ),
        migrations.AlterField(
            model_name='resumecandidate',
            name='stage',
            field=models.CharField(db_index=True, default='phone_interview', max_length=100, verbose_name='Этап процесса'),
        ),
        migrations.AlterField(
            model_name='resumestage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название этапа процесса'),
        ),
    ]
