# Generated by Django 6.0.3 on 2026-04-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0016_alter_resumestage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumecandidate',
            name='department_call_approval',
            field=models.CharField(choices=[('pending', 'Не рассмотрено'), ('approved', 'Согласован к вызову'), ('rejected', 'Не согласован к вызову')], db_index=True, default='pending', max_length=20, verbose_name='Согласование к вызову'),
        ),
        migrations.AddField(
            model_name='resumecandidate',
            name='department_call_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий соответствующего отдела'),
        ),
        migrations.AddField(
            model_name='resumecandidate',
            name='security_approval',
            field=models.CharField(choices=[('pending', 'Не рассмотрено'), ('approved', 'Согласовано'), ('rejected', 'Не согласовано')], db_index=True, default='pending', max_length=20, verbose_name='Служба безопасности'),
        ),
        migrations.AddField(
            model_name='resumecandidate',
            name='security_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий службы безопасности'),
        ),
        migrations.AddField(
            model_name='resumecandidate',
            name='security_refusal_reason',
            field=models.TextField(blank=True, verbose_name='Причина отказа службы безопасности'),
        ),
        migrations.AlterField(
            model_name='resumecandidate',
            name='approval_department',
            field=models.CharField(blank=True, choices=[('', 'Не требуется'), ('mechanic_approval', 'ОГМ'), ('geology_approval', 'Геологический отдел'), ('surveyor_approval', 'Отдел маркшейдера'), ('transport_approval', 'Транспортный цех')], db_index=True, default='', max_length=100, verbose_name='Требуется согласование'),
        ),
    ]
