# Generated by Django 6.0.3 on 2026-04-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0018_alter_resumecandidate_approval_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumecandidate',
            name='approval_department',
            field=models.CharField(blank=True, choices=[('', 'Не требуется'), ('otipb', 'ОТИПБ'), ('mechanic_approval', 'ОГМ'), ('geology_approval', 'Геологический отдел'), ('surveyor_approval', 'Отдел маркшейдера'), ('transport_approval', 'Транспортный цех')], db_index=True, default='', max_length=100, verbose_name='Какой отдел отвечает'),
        ),
        migrations.AlterField(
            model_name='resumecandidate',
            name='department_call_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий отдела'),
        ),
    ]
