# Generated by Django 6.0.3 on 2026-04-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0019_alter_resumecandidate_approval_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumecandidate',
            name='department_call_approval',
            field=models.CharField(blank=True, choices=[('pending', 'Не рассмотрено'), ('approved', 'Согласован к вызову'), ('rejected', 'Не согласован к вызову')], db_index=True, default='pending', max_length=20, verbose_name='Согласование к вызову'),
        ),
        migrations.AlterField(
            model_name='resumecandidate',
            name='security_approval',
            field=models.CharField(blank=True, choices=[('pending', 'Не рассмотрено'), ('approved', 'Согласовано'), ('rejected', 'Не согласовано')], db_index=True, default='pending', max_length=20, verbose_name='Служба безопасности'),
        ),
    ]
