# Generated by Django 6.0.3 on 2026-04-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0020_alter_resumecandidate_department_call_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumecandidate',
            name='estimated_arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='Расчетная дата приезда'),
        ),
        migrations.AlterField(
            model_name='resumecandidate',
            name='stage',
            field=models.CharField(blank=True, db_index=True, default='phone_interview', max_length=100, verbose_name='Этап процесса'),
        ),
    ]
