# Generated by Django 6.0.3 on 2026-04-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0021_resumecandidate_estimated_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumecandidate',
            name='medical_commission',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидает направления'), ('issued', 'Выдано направление'), ('passed', 'Пройдена медкомиссия'), ('failed', 'Не пройдена')], default='pending', max_length=20, verbose_name='Мед комиссия'),
        ),
    ]
