# Generated by Django 6.0.3 on 2026-04-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0022_alter_resumecandidate_medical_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumecandidate',
            name='otipb_approval',
            field=models.CharField(blank=True, choices=[('pending', 'Не рассмотрено'), ('approved', 'Согласовано'), ('rejected', 'Не согласовано')], db_index=True, default='pending', max_length=20, verbose_name='ОТИПБ'),
        ),
        migrations.AddField(
            model_name='resumecandidate',
            name='otipb_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий ОТИПБ'),
        ),
        migrations.AddField(
            model_name='resumecandidate',
            name='otipb_refusal_reason',
            field=models.TextField(blank=True, verbose_name='Причина отказа ОТИПБ'),
        ),
    ]
