# Generated by Django 6.0.3 on 2026-04-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0023_resumecandidate_otipb_approval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumecandidate',
            name='otipb',
        ),
        migrations.AlterField(
            model_name='resumecandidate',
            name='approval_department',
            field=models.CharField(blank=True, choices=[('', 'Не требуется'), ('mechanic_approval', 'ОГМ'), ('geology_approval', 'Геологический отдел'), ('surveyor_approval', 'Отдел маркшейдера'), ('transport_approval', 'Транспортный цех')], db_index=True, default='', max_length=100, verbose_name='Какой отдел отвечает'),
        ),
    ]
