# Generated by Django 6.0.3 on 2026-04-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0024_remove_resumecandidate_otipb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatesourcerecord',
            name='medical_direction',
        ),
        migrations.RemoveField(
            model_name='candidatesourcerecord',
            name='otipb',
        ),
        migrations.AddField(
            model_name='candidatesourcerecord',
            name='med_result',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидает направления'), ('issued', 'Выдано направление'), ('passed', 'Пройдена медкомиссия')], default='pending', max_length=20, verbose_name='Направление на МО'),
        ),
        migrations.AlterField(
            model_name='resumecandidate',
            name='medical_commission',
            field=models.CharField(blank=True, choices=[('pending', 'Ожидает направления'), ('issued', 'Выдано направление'), ('passed', 'Пройдена медкомиссия')], default='pending', max_length=20, verbose_name='Мед комиссия'),
        ),
    ]
