# Generated by Django 6.0.3 on 2026-05-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0025_remove_candidatesourcerecord_medical_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumecandidate',
            name='chief_engineer_approval',
            field=models.CharField(blank=True, choices=[('pending', 'Не рассмотрено'), ('approved', 'Согласовано'), ('rejected', 'Не согласовано')], db_index=True, default='pending', max_length=20, verbose_name='Главный инженер'),
        ),
        migrations.AddField(
            model_name='resumecandidate',
            name='chief_engineer_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий главного инженера'),
        ),
    ]
