# Generated by Django 5.2.1 on 2026-03-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DebitorComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account", models.CharField(max_length=100, verbose_name="Счет")),
                (
                    "subkonto1",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Субконто 1"
                    ),
                ),
                (
                    "subkonto2",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Субконто 2"
                    ),
                ),
                (
                    "subkonto3",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Субконто 3"
                    ),
                ),
                (
                    "report_date",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Дата отчета"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Комментарий по дебиторке",
                "verbose_name_plural": "Комментарии по дебиторке",
                "unique_together": {
                    ("account", "subkonto1", "subkonto2", "subkonto3", "report_date")
                },
            },
        ),
    ]
