# Generated by Django 5.2.1 on 2026-03-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DebitorCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account", models.CharField(max_length=100, verbose_name="Счет")),
                (
                    "subkonto1",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Субконто 1"
                    ),
                ),
                (
                    "subkonto2",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Субконто 2"
                    ),
                ),
                (
                    "subkonto3",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Субконто 3"
                    ),
                ),
                (
                    "report_date",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Дата отчета"
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("accounting", "Бухгалтерия"),
                            ("supply", "Снабжение"),
                            ("legal", "Юридический отдел"),
                            ("closed", "Закрыто"),
                        ],
                        default="accounting",
                        max_length=30,
                        verbose_name="Этап",
                    ),
                ),
                (
                    "debt_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Причина образования ДЗ"
                    ),
                ),
                (
                    "responsible_person",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ответственный",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Карточка дебиторской задолженности",
                "verbose_name_plural": "Карточки дебиторской задолженности",
                "unique_together": {
                    ("account", "subkonto1", "subkonto2", "subkonto3", "report_date")
                },
            },
        ),
        migrations.DeleteModel(
            name="DebitorComment",
        ),
    ]
