# Generated by Django 5.2.1 on 2026-03-07 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_debitorcase_delete_debitorcomment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="debitorcase",
            unique_together={("account", "subkonto1", "subkonto2", "subkonto3")},
        ),
        migrations.AddField(
            model_name="debitorcase",
            name="current_date",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Дата операции"
            ),
        ),
        migrations.AddField(
            model_name="debitorcase",
            name="current_debt_date",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Дата образования задолженности",
            ),
        ),
        migrations.AddField(
            model_name="debitorcase",
            name="current_debt_period",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Период задолженности",
            ),
        ),
        migrations.AddField(
            model_name="debitorcase",
            name="current_debt_reason_excel",
            field=models.TextField(
                blank=True, null=True, verbose_name="Причина ДЗ из Excel"
            ),
        ),
        migrations.AddField(
            model_name="debitorcase",
            name="current_debt_term",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Срок дебиторской задолженности",
            ),
        ),
        migrations.AddField(
            model_name="debitorcase",
            name="current_records_count",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Количество записей"
            ),
        ),
        migrations.AddField(
            model_name="debitorcase",
            name="current_responsible_department_excel",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Отдел из Excel"
            ),
        ),
        migrations.AddField(
            model_name="debitorcase",
            name="current_sum_dt",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Текущая сумма остаток Дт"
            ),
        ),
        migrations.AddField(
            model_name="debitorcase",
            name="current_sum_kt",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Текущая сумма остаток Кт"
            ),
        ),
        migrations.AddField(
            model_name="debitorcase",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AddField(
            model_name="debitorcase",
            name="last_report_date",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Последняя дата отчета",
            ),
        ),
        migrations.RemoveField(
            model_name="debitorcase",
            name="report_date",
        ),
        migrations.CreateModel(
            name="DebitorSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_date",
                    models.CharField(max_length=50, verbose_name="Дата отчета"),
                ),
                (
                    "date",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Дата"
                    ),
                ),
                (
                    "sum_dt",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Сумма остаток Дт"
                    ),
                ),
                (
                    "sum_kt",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Сумма остаток Кт"
                    ),
                ),
                (
                    "records_count",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Количество записей",
                    ),
                ),
                (
                    "debt_date",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Дата образования задолженности",
                    ),
                ),
                (
                    "debt_term",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Срок дебиторской задолженности",
                    ),
                ),
                (
                    "debt_period",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Период задолженности",
                    ),
                ),
                (
                    "debt_reason_excel",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Причина образования ДЗ из Excel",
                    ),
                ),
                (
                    "responsible_department_excel",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Ответственный отдел из Excel",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="main.debitorcase",
                        verbose_name="Карточка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Снимок дебиторской задолженности",
                "verbose_name_plural": "Снимки дебиторской задолженности",
                "ordering": ["-report_date", "-id"],
                "unique_together": {("case", "report_date")},
            },
        ),
    ]
