# Generated by Django 5.2.1 on 2026-03-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_debitorcase_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debitorcase",
            name="current_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата операции"),
        ),
        migrations.AlterField(
            model_name="debitorcase",
            name="current_debt_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата образования задолженности"
            ),
        ),
        migrations.AlterField(
            model_name="debitorcase",
            name="last_report_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Последняя дата отчета"
            ),
        ),
        migrations.AlterField(
            model_name="debitorsnapshot",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="debitorsnapshot",
            name="debt_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата образования задолженности"
            ),
        ),
        migrations.AlterField(
            model_name="debitorsnapshot",
            name="report_date",
            field=models.DateField(verbose_name="Дата отчета"),
        ),
    ]
