# Generated by Django 6.0.3 on 2026-04-28 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Подразделение')),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='Код')),
                ('warehouse_aliases', models.TextField(blank=True, help_text='Каждое название с новой строки. Например: Склад Дражный.', verbose_name='Склады/получатели из 1С')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('users', models.ManyToManyField(blank=True, related_name='transfer_departments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи подразделения')),
            ],
            options={
                'verbose_name': 'Подразделение по перемещениям',
                'verbose_name_plural': 'Подразделения по перемещениям',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TransferImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='transfers/imports/%Y/%m/%d/', verbose_name='Файл Excel')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Исходное имя файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('period_text', models.CharField(blank=True, max_length=255, verbose_name='Период из файла')),
                ('rows_count', models.PositiveIntegerField(default=0, verbose_name='Строк обработано')),
                ('orders_count', models.PositiveIntegerField(default=0, verbose_name='Заказов обновлено')),
                ('items_count', models.PositiveIntegerField(default=0, verbose_name='Позиций обновлено')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка импорта')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_import_batches', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Загрузка перемещений',
                'verbose_name_plural': 'Загрузки перемещений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Номер заказа')),
                ('order_title', models.CharField(blank=True, max_length=255, verbose_name='Заказ на перемещение')),
                ('order_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата заказа')),
                ('movement_numbers', models.TextField(blank=True, verbose_name='Документы перемещения')),
                ('last_movement_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Последнее перемещение')),
                ('responsible_name', models.CharField(blank=True, max_length=255, verbose_name='Ответственный 1С')),
                ('sender_warehouse', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Склад отправитель')),
                ('receiver_warehouse', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Склад получатель')),
                ('status', models.CharField(choices=[('requested', 'Ожидает оформления'), ('issued', 'Отгружено со склада'), ('in_transit', 'В пути'), ('delivered', 'Доставлено'), ('canceled', 'Отменено')], db_index=True, default='requested', max_length=30, verbose_name='Статус')),
                ('planned_delivery_at', models.DateTimeField(blank=True, null=True, verbose_name='Плановая доставка')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Фактическая доставка')),
                ('driver_name', models.CharField(blank=True, max_length=255, verbose_name='Водитель/экспедитор')),
                ('vehicle_number', models.CharField(blank=True, max_length=100, verbose_name='Транспорт')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_transfer_orders', to=settings.AUTH_USER_MODEL, verbose_name='Отметил доставку')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='transfers.transferdepartment', verbose_name='Подразделение')),
                ('last_import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='transfers.transferimportbatch', verbose_name='Последняя загрузка')),
            ],
            options={
                'verbose_name': 'Заказ на перемещение',
                'verbose_name_plural': 'Заказы на перемещение',
                'ordering': ['status', '-order_date', '-updated_at'],
                'permissions': [('view_all_transferorder', 'Может видеть все перемещения'), ('manage_transfer_delivery', 'Может менять доставку перемещений')],
            },
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(db_index=True, max_length=500, verbose_name='Номенклатура')),
                ('quantity_requested', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='К оформлению Приход')),
                ('quantity_moved', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='К оформлению Расход')),
                ('movement_numbers', models.TextField(blank=True, verbose_name='Документы перемещения по позиции')),
                ('source_rows', models.TextField(blank=True, verbose_name='Строки исходного файла')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transfers.transferorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позиция перемещения',
                'verbose_name_plural': 'Позиции перемещений',
                'ordering': ['item_name'],
                'unique_together': {('order', 'item_name')},
            },
        ),
    ]
