# Generated by Django 5.2.1 on 2026-03-06 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Подразделение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Подразделение",
                "verbose_name_plural": "Подразделения",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "machine_brand",
                    models.CharField(max_length=255, verbose_name="Марка техники"),
                ),
                (
                    "inventory_number",
                    models.CharField(max_length=100, verbose_name="Инв. номер"),
                ),
                (
                    "maintenance_date",
                    models.DateField(verbose_name="Дата проведения ТО"),
                ),
                (
                    "responsible_fio",
                    models.CharField(max_length=255, verbose_name="ФИО ответственного"),
                ),
                (
                    "machine_hours",
                    models.PositiveIntegerField(verbose_name="Машиночасы"),
                ),
                (
                    "maintenance_number",
                    models.CharField(
                        max_length=100, verbose_name="Номер проведения ТО"
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(max_length=100, verbose_name="Вид ТО"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="maintenance.department",
                        verbose_name="Подразделение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Техническое обслуживание",
                "verbose_name_plural": "Техническое обслуживание",
                "ordering": ["-maintenance_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceTaskFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_name", models.TextField(verbose_name="Работа")),
                (
                    "detail_group",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Группа деталей",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "catalog_number",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Кат. №"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Ед. изм."
                    ),
                ),
                (
                    "qty_plan",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Количество план"
                    ),
                ),
                (
                    "qty_fact",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Количество факт"
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="maintenance.maintenancerecord",
                        verbose_name="Документ ТО",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка ТО",
                "verbose_name_plural": "Строки ТО",
                "ordering": ["id"],
            },
        ),
    ]
