# Generated by Django 6.0.3 on 2026-03-15 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregateJournalUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='aggregate_journal/%Y/%m/', verbose_name='Файл Excel')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('importing', 'Импортируется'), ('done', 'Импортирован'), ('error', 'Ошибка')], db_index=True, default='new', max_length=20, verbose_name='Статус')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('imported_at', models.DateTimeField(blank=True, null=True, verbose_name='Импортирован')),
                ('rows_count', models.PositiveIntegerField(default=0, verbose_name='Количество строк')),
                ('error_text', models.TextField(blank=True, verbose_name='Текст ошибки')),
            ],
            options={
                'verbose_name': 'Загрузка агрегатного журнала',
                'verbose_name_plural': 'Загрузки агрегатного журнала',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AggregateJournalRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_number', models.PositiveIntegerField(default=0, verbose_name='Номер строки в Excel')),
                ('department', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Подразделение')),
                ('machine_brand', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Марка')),
                ('modification', models.CharField(blank=True, default='', max_length=255, verbose_name='Модификация')),
                ('inventory_number', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Инвентарный номер')),
                ('maintenance_start_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата начала обслуживания')),
                ('maintenance_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания обслуживания')),
                ('actual_hours_at_maintenance', models.FloatField(blank=True, null=True, verbose_name='Фактическая наработка в момент проведения ТО')),
                ('machine_hours', models.FloatField(blank=True, null=True, verbose_name='Наработка машины')),
                ('maintenance_type', models.CharField(blank=True, default='', max_length=255, verbose_name='Вид ТО')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='maintenance.aggregatejournalupload', verbose_name='Загрузка')),
            ],
            options={
                'verbose_name': 'Строка агрегатного журнала',
                'verbose_name_plural': 'Строки агрегатного журнала',
                'ordering': ['-maintenance_start_date', '-id'],
                'indexes': [models.Index(fields=['maintenance_start_date'], name='maintenance_mainten_6343a9_idx'), models.Index(fields=['machine_brand', 'inventory_number'], name='maintenance_machine_a16c33_idx'), models.Index(fields=['department', 'machine_brand'], name='maintenance_departm_6a3936_idx')],
            },
        ),
    ]
